glyptodon/guacamole-server

- src/protocols/ssh/ssh_client.c
- src/protocols/ssh/ssh_key.c
- src/protocols/ssh/ssh_key.h
Auth keys are actually properly handled - logging of errors is simply lacking or confusing. This change addresses that deficiency.
> GUAC-974: Add logging and error reporting to avoid key confusion.

- src/common/guac_surface.c
The surface code previously (and erroneously) reset the clipping rectangle whenever the surface was resized. It now simply adjusts the clipping rectangle to fit within the new surface dimensions.
Similarly, the old code would copy data using the clipping rectangle as the basis for that copy, under the assumption it would occupy the entire surface. This is fixed, too.
> GUAC-996: Do not reset clip upon resize. Fix copy of surface data.

- src/common/guac_surface.c
- src/common/guac_surface.h
Since the surface used by the terminal code resizes (unlike VNC) and does not use clipping (unlike RDP), recent changes in GUAC-996 caused a regression not noticed during testing (which was restricted to VNC and RDP).
When the clipping rectangle is updated to fit within the new display size, this only makes sense when a clipping rectangle has actually been set. In the case of RDP, the clipping rectangle is reset after each drawing operation, but the terminal code will only reset the clipping rectangle in when the surface is allocated, at which point the rectangle is 0x0, thus everything is clipped.
This change properly initializes the clipping rectangle when clipping is used, and does not pay attention to the clipping rectangle unless it has been explicitly set, thanks to a "clipped" …
> GUAC-1008: Properly init clipping rectangle.

- configure.ac
- src/protocols/rdp/rdp_bitmap.c
- src/protocols/rdp/rdp_color.c
FreeRDP 1.2.0-beta1+android9 has different parameters for the recently-added ```interleaved_decompress()``` and ```planar_decompress()``` functions. It also adds a new color conversion function, and renders the old color conversion function useless.
> GUAC-994: Fix build against 1.2.0-beta1+android9.

- src/terminal/display.c
- src/terminal/display.h
- src/terminal/terminal.c
As a precursor to the GUAC-803 scrollbar for the guac terminal, this change moves the terminal display into its own layer. This isolates the display of text from other things (the future scrollbar), and has the nice side effect of ensuring the default layer is always the same size as the client (no more fuzzy text).
> GUAC-803: Move display into separate layer.

- src/terminal/Makefile.am
- src/terminal/scrollbar.c
- src/terminal/scrollbar.h
- src/terminal/terminal.c
- src/terminal/terminal.h
This change adds a scrollbar to the right of the terminal display, always attached to the right side of the client display. The scrollbar updates based on the current scroll position and size of the display relative to the scrollback buffer.
The scrollbar is not yet interactive. I'll take care of that in a different PR.
> GUAC-803: Add scrollbar to right of terminal display.

- src/libguac/client.c
- src/libguac/guacamole/client.h
- src/libguac/guacamole/user.h
- src/libguac/user-handlers.c
- src/libguac/user.c
- src/protocols/vnc/vnc.c
This change adds lag statistics to the ```guac_user``` structure, and automatically updates them as ```sync``` instructions are received from connected users. Client plugins can then use ```guac_client_get_processing_lag()``` to approximate the processing lag experienced by the connected pool of users, and adjust server-side frame duration accordingly.
The VNC client had been updated to use ```guac_client_get_processing_lag()``` appropriately.
> GUAC-889: Implement lag control

- src/terminal/Makefile.am
- src/terminal/pointer.c
- src/terminal/pointer.h
- src/terminal/scrollbar.c
- src/terminal/scrollbar.h
- src/terminal/terminal.c
- src/terminal/terminal.h
This change adds mouse support to the existing scrollbar, allowing the current scroll offset to be updated via clicking and dragging the scrollbar handle. The mouse cursor is updated appropriately when over the scrollbar.
> GUAC-803: Add mouse support to scrollbar

- src/terminal/Makefile.am
- src/terminal/common.c
- src/terminal/common.h
- src/terminal/packet.c
- src/terminal/packet.h
- src/terminal/terminal.c
- src/terminal/terminal.h
The old terminal code would redraw unnecessarily frequently for changes to the display not initiated by data received over STDOUT. This change allows external code to notify the terminal of non-STDOUT changes, thereby unblocking the pending frame and causing a flush, grouping changes as much as possible.
> GUAC-803: Make terminal updates more efficient

- src/terminal/terminal.c
This change fixes a race condition during resize of the Guacamole terminal. The terminal lock is not acquired during resize, thus a flush to the underlying surface may occur while the newly-resized surface is not yet finished being allocated, leading to a segfault.
> GUAC-1028: Fix race condition on terminal resize.

- configure.ac
The ```freerdp_channels_new()``` function is not always included in libfreerdp-client, depending on the FreeRDP version in question, and its absence can result in libfreerdp-client not being linked in if:
1. The platform on which guacamole-server is built (correctly) does not automatically link against implied dependencies ([Fedora](http://fedoraproject.org/wiki/Features/ChangeInImplicitDSOLinking), for example).
2. The FreeRDP version puts ```freerdp_channels_new()``` in libfreerdp-core instead of libfreerdp-client.
> GUAC-1005: Include libfreerdp-core in test for freerdp_channels_new()

- src/protocols/rdp/guac_rdpdr/rdpdr_printer.c
Solves the issue reported in: GUAC-570
The problem of blank pages occuring inside the generated PDF (only if it exceeds 11 pages) is due to gs generated output such as: 
%%[Page: 1]%%
%%[Page: 2]%%
...
%%[Page: n]%%
...
being written to the stdout and thus incorporated in the output PDF file. 
This tracing appear in blocks, mixed within the PDF source and make some of the pdf pages inconsistent (not formally correct).
> GUAC-570: Solves the issue of blank pages occuring inside generated PDFs having 11 or more pages

- AUTHORS
- configure.ac
- doc/Doxyfile
- src/guacd/man/guacd.8
- src/guacd/man/guacd.conf.5
This change brings guacamole-server up to date with respect to new contributors, and bumps the version number of the project.
Unlike 0.9.4, no changes at all were made to libguac, so the libtool versioning is untouched. A 0.9.4 build of libguac will be completely identical to a 0.9.5 build of libguac.
> GUAC-1018: Update guacamole-server for 0.9.5 release.

- src/common/guac_surface.c
A long series of changes has resulted in RDP updates *not* being clipped within surface bounds unless an explicit clipping rectangle is present. This change ensures that all updates are clipped within surface bounds, regardless of the presence or absence of a clipping rectangle.
> GUAC-1090: Clip operation by surface size when no clipping rectangle is present.

- src/protocols/rdp/rdp_bitmap.c
When FreeRDP receives a bitmap update from the RDP server, it calls a supplied decompression function to handle decompression and assign the resulting data to the ```bitmap->data``` pointer. FreeRDP will also occasionally reuse past bitmap cache entries. This is all fine.
Unfortunately, the bitmap free function supplied by the implementation is only invoked *after* decompression. This will properly result in implementation-specific data being freed, but since the decompression function *must* assign to ```bitmap->data``` by definition, a memory leak will result if that decompression function does not also free anything already in ```bitmap->data```.
> GUAC-1095: Free any existing bitmap data prior to overwriting the bitmap data pointer.

- configure.ac
- doc/Doxyfile
No changes to libguac this time. Only RDP and VNC were affected by this release.
> GUAC-1174: Bump version numbers to 0.9.7.

- src/terminal/display.c
Pango/Cairo's handling of DPI is sometimes buggy - it reports the size of glyphs correctly, but renders them at constant 96 DPI.
> GUAC-1226: Do not rely on Pango/Cairo for DPI handling - simply scale the font size.

- src/libguac/Makefile.am
In preparation for the API changes of GUAC-1172, I've run into the rather ugly mix of tabs and spaces within libguac's `Makefile.am`. To avoid a correspondingly-ugly diff and pull request, I'm fixing this now.
> GUAC-1172: Fix indentation within libguac Makefile.am.

- src/libguac/Makefile.am
- src/libguac/client-handlers.c
- src/libguac/client-handlers.h
- src/libguac/client.c
- src/libguac/guacamole/client-constants.h
- src/libguac/guacamole/client-fntypes.h
- src/libguac/guacamole/client.h
- src/libguac/guacamole/object-types.h
- src/libguac/guacamole/object.h
- src/libguac/guacamole/protocol.h
- src/libguac/protocol.c
To facilitate exposure of entire filesystems, we're adding a new system similar to the existing streaming pattern already part of the Guacamole protocol: objects. A Guacamole protocol object functions as a set of named streams, each of which can be read from or written to by the `get` or `put` instruction respectively.
The `get` and `put` instructions result in the creation of streams within the context of the object. In the case of `put`, the stream is created directly, while the stream in response to a `get` must be created using a `body` instruction. This is in line with the existing stream pattern of the Guacamole protocol, where the side of the conversation sending the data must create the stream, and does so through an instruction which associates an index with metainformation …
> GUAC-1172: Implement libguac side of Guacamole protocol objects.

- src/protocols/ssh/client.c
- src/protocols/ssh/client.h
- src/protocols/ssh/guac_handlers.c
- src/protocols/ssh/sftp.c
- src/protocols/ssh/sftp.h
- src/protocols/ssh/ssh_client.c
This change exposes SFTP functionality through Guacamole's new filesystem object, allowing direct listing of directories and upload/download of files (without requiring the use of `guacctl`).
The old mechanism using `guacctl` is unaffected, and continues to be supported.
> GUAC-1172: Add filesystem object support to SSH/SFTP.

- src/protocols/ssh/sftp.c
The JSON streaming functions of the current SFTP filesystem code would send the following invalid JSON when a directory is empty:
```
}
```
This change ensures that the leading brace of the JSON object is written, even if there are no properties within the object.
> GUAC-1172: Ensure empty directories are valid JSON.

- src/common/Makefile.am
- src/common/guac_json.c
- src/common/guac_json.h
- src/protocols/ssh/sftp.c
- src/protocols/ssh/sftp.h
Prior to adding filesystem support to RDP, the JSON streaming code added to the SSH support must be moved to a common location. This change does exactly that.
> GUAC-1172: Move JSON functions to common.

- src/common/guac_json.c
- src/common/guac_json.h
- src/protocols/rdp/guac_rdpdr/rdpdr_fs_service.c
- src/protocols/rdp/rdp_fs.c
- src/protocols/rdp/rdp_fs.h
- src/protocols/rdp/rdp_status.h
- src/protocols/rdp/rdp_stream.c
- src/protocols/rdp/rdp_stream.h
This change adds support for Guacamole's new filesystem objects (and thus file browsing) to the existing RDP file transfer support. The changes are modeled after the changes made to SSH to support the same, but follow the established `guac_rdp_stream` pattern from past RDP changes.
FreeRDP does some things which clash with use of the standard `bool` type provided by `stdbool.h`, so I've also had to remove use of `bool` from the new `guac_json` functions added to common.
> GUAC-1172: Implement filesystem object support for RDP.

- configure.ac
- src/common-ssh/guac_sftp.c
- src/common-ssh/guac_ssh.c
- src/common-ssh/guac_ssh_key.c
- src/common-ssh/guac_ssh_user.c
- src/protocols/rdp/Makefile.am
- src/protocols/rdp/client.c
- src/protocols/rdp/client.h
- src/protocols/rdp/guac_handlers.c
- src/protocols/rdp/rdp_stream.c
- src/protocols/rdp/sftp.c
- src/protocols/rdp/sftp.h
- src/protocols/vnc/Makefile.am
- src/protocols/vnc/client.c
- src/protocols/vnc/client.h
- src/protocols/vnc/guac_handlers.c
- src/protocols/vnc/sftp.c
- src/protocols/vnc/sftp.h
This change leverages the new, common SSH core to add SFTP file transfer support to both VNC and RDP. This functions independently of any existing file transfer support, thus you can technically have two remote filesystems by setting both `enable-drive` and `enable-sftp` to `true` on an RDP connection.
> GUAC-1171: Add support for SFTP file transfer to VNC and RDP.

- src/protocols/rdp/client.c
The values of the `guac_rdp_settings` struct may be `NULL`, and indeed are expected to be `NULL` if not specified. Their values should be used as defaults only if not `NULL`.
> GUAC-1171: RDP settings values may be NULL.

- src/common-ssh/guac_sftp.c
- src/common-ssh/guac_sftp.h
- src/common-ssh/guac_ssh.c
- src/common-ssh/guac_ssh.h
- src/protocols/rdp/client.c
- src/protocols/rdp/client.h
- src/protocols/rdp/guac_handlers.c
- src/protocols/ssh/client.c
- src/protocols/ssh/client.h
- src/protocols/ssh/guac_handlers.c
- src/protocols/ssh/ssh_client.c
- src/protocols/vnc/client.c
- src/protocols/vnc/client.h
- src/protocols/vnc/guac_handlers.c
SFTP password passing for SSH and RDP was recently broken due to:
1. Broken logic within SSH parameter parsing (password auth would only be used if the password was **missing**).
2. Bad values within RDP (the "sftp-username" parameter was used for the password by mistake).
These issues lead to segfaults due to the lack of proper error handling in the newly-common SSH functions. If an auth attempt was made without any credentials whatsoever (as would universally happen due to the above breakage), the function would segfault rather than fail cleanly with a meaningful error. This PR should fix all that.
Additionally, even after all this was addressed, the greedily-automatic nature of the various `guac_common_ssh_destroy_*()` functions lead to possible double-free corruption if a user object …
> GUAC-1264: Fix segfault in password handling

- src/protocols/vnc/client.c
- src/protocols/vnc/client.h
- src/protocols/vnc/clipboard.c
- src/protocols/vnc/vnc_handlers.c
Although VNC mandates ISO8859-1, some VNC servers deviate from this and allow Unicode. ESXi is one of these - from @flangelo in #52:
> The ESXi VNC server supports UTF-8, this is what we're using.
This PR merges the changes contributed in #52, brought up to date with master, and modifies to match recent comment style.
I've also modified the parsing of encoding names, such that unknown encodings are defaulted to ISO8859-1 with a warning, rather than silently.
> GUAC-298: Configurable VNC clipboard encoding

- AUTHORS
- src/protocols/rdp/client.c
- src/protocols/rdp/rdp_fs.c
- src/protocols/rdp/rdp_fs.h
- src/protocols/rdp/rdp_settings.h
This change merges (and rebases) the changes made with #33. Additionally, I have modified the automatic creation of drive path such that any errors in creation are logged at the error level, rather than at debug level.
> GUAC-515: Automatically create RDP drive path if requested.

- src/protocols/ssh/client.c
- src/protocols/telnet/client.c
- src/terminal/display.c
- src/terminal/display.h
- src/terminal/scrollbar.c
- src/terminal/terminal.c
- src/terminal/terminal.h
This change allows the palette (or, rather, the default foreground and background) of SSH and telnet sessions to be selected through standardized color scheme names, currently: `black-white`, `gray-black`, `green-black`, `white-black`. Each of these names follows the pattern `foreground-background`.
As the background color of the terminal as a whole may change, I've also altered the style of the scrollbar such that it looks alright regardless of background.
> GUAC-1195: Add color schemes to SSH and telnet.

- configure.ac
- src/libguac/Makefile.am
- src/libguac/guacamole/protocol.h
- src/libguac/protocol.c
Changes picked and rebased from #62 to reduce overall scope. These changes add support for the new `jpeg` instruction through the `guac_protocol_send_jpeg()` function, and add the necessary JPEG dependencies to the build.
> GUAC-240: Implement support for JPEG instruction.

- configure.ac
- src/libguac/protocol.c
Older versions of libjpeg, such as version 6b, lack the `jpeg_mem_dest()` function required by Guacamole as of recent [GUAC-240](https://glyptodon.org/jira/browse/GUAC-240) changes (see c27e299). This breaks the Guacamole build on several platforms, including CentOS 6.
This change adds support for older versions of libjpeg by providing an internal implementation of `jpeg_mem_dest()` if libjpeg does not provide its own.
> GUAC-1285: Add support for libjpeg6b

- src/protocols/vnc/client.h
This change increases the `GUAC_VNC_FRAME_TIMEOUT` from 0ms to 10ms so more VNC messages can be handled each frame.
> GUAC-1290: Increase VNC frame timeout to 10ms

- src/protocols/telnet/guac_handlers.c
This change adds support for telnet's IAC ("interpret as command") BRK ("break"), sending IAC BRK   whenever `Pause`, `Break`, or `Ctrl`+`0` are pressed.
The BRK command is different from control codes like `^C` and has different semantics. Though usually initiated using the keyboard, including our implementation, it is not technically keyboard input.
Traditionally, sending a break meant leaving the data line in a logical zero state for a prescribed amount of time (somewhere on the order of a few hundred milliseconds). Telnet, lacking such a data line, uses its own IAC system to accomplish this.
When connected to a Linux terminal, receiving BRK causes SIGINT or SIGBREAK to be sent to the child processes of that terminal. Low-level hardware which supports telnet also often assigns purpose …
> GUAC-1296: Send IAC BRK when Pause, Break, or Ctrl+0 are pressed.

- Makefile.am
- src/guacd/Makefile.am
Each `Makefile` is generally free to use whatever whitespace it likes .... *EXCEPT* preceding the commands within a recipe, where tab characters are strictly required by the `Makefile` syntax. Necessary tabs were replaced with spaces in commit c199cfc, breaking the build on platforms where this is enforced.
This PR changes those spaces back to tabs, and removes the indent entirely in a few cases where it technically should be absent (between automake macros).
> GUAC-1297: Remove indentation / use tabs where required by Makefile standard.

- configure.ac
- doc/Doxyfile
- src/guacd/man/guacd.8
- src/guacd/man/guacd.conf.5
- src/libguac/Makefile.am
This change bumps the version of guacamole-server to 0.9.8 to match the upcoming release. The libtool versioning must be bumped up a full release number (without backward compatibility) as this release removes `guac_protocol_send_png()` in favor of the more generic (and faster and more efficient) `guac_protocol_send_img()`.
Any previous usages of `guac_protocol_send_png()` should be replaced with `guac_client_stream_png()` which leverages `guac_protocol_send_img()` behind the scenes. This release of libguac is otherwise completely API-compatible with 0.9.7, though not ABI-compatible.
> GUAC-1280: Bump version numbers to 0.9.8. Update libtool versioning.

- src/protocols/vnc/pulse.c
PulseAudio has the unfortunate habit of constantly streaming data, even when that data is nothing but silence (null bytes). This change works around this issue by only sending data received from PulseAudio if it is *not* silence, or if data is present in the audio buffer that will not be flushed otherwise.
> GUAC-427: Avoid sending silence received from PulseAudio.

- src/common/guac_surface.c
From a CI build of the recent merge of the experimental branch to master:
guac_surface.c: In function 'guac_common_surface_flush':
guac_surface.c:360:20: error: 'last_pixel' may be used uninitialized in this function [-Werror=maybe-uninitialized]
guac_surface.c:349:18: note: 'last_pixel' was declared here
This is actually untrue - it is impossible for `last_pixel` to be uninitialized here, but the compiler in use in this build environment differs from the compiler used in the past, and this particular warning is a little less selective. For what it's worth, even the function name is incorrect here - the lines in question are actually within the function `__guac_common_surface_png_optimality()`.
I've modified things such that `last_pixel` is obviously initialized, without making that …
> GUAC-240: Ensure initialization of last_pixel is obvious.

- src/guacd/daemon.c
- src/libguac/guacamole/client.h
This change adds a new instruction, `image`, to the Guacamole protocol handshake. This instruction lists the image formats supported by the client side. It is safe to assume that this list will contain `image/png` and `image/jpeg`, though a properly-functioning client implementation will still perform these checks and include the mimetypes in the handshake anyway.
> GUAC-1305: Add image mimetypes to Guacamole protocol handshake.

- src/common/guac_surface.c
- src/libguac/client.c
- src/libguac/encode-webp.c
- src/libguac/encode-webp.h
- src/libguac/guacamole/client.h
We can't use WebP instead of PNG as there are quite a few cases where PNG is *far* better, and those cases occur extremely frequently in typical use of guac, but it does make sense to at least provide the support at an API level.
I made these changes expecting the WebP vs. PNG experiment to come out in favor of WebP. This did not happen, but the changes are still sound.
> GUAC-1305: Support lossless WebP within encoder.

- src/guacd/daemon.c
- src/libguac/client.c
- src/libguac/guacamole/client.h
The storage used for instruction arguments *cannot* be relied upon between reads. The buffers used to store instruction data are reused with subsequent read calls. For GUAC-1305, this has the effect of WebP suddenly becoming disabled later on in the connection, as the stored mimetypes no longer match.
This change copies the mimetypes received during the handshake into dynamically-allocated storage which is freed upon disconnect.
> GUAC-1305: Copy mimetypes - do not just point instruction storage

- src/libguac/guacamole/protocol.h
- src/libguac/protocol.c
The duration is no longer needed, as the Guacamole client will play received video back immediately.
> GUAC-1354: Remove duration from video instruction.

- src/libguac/socket.c
The `__keep_alive_enabled` flag is used by `guac_socket` to determine whether the keep alive thread is running. The thread is disabled by default, and this flag absolutely **must** reflect that. Doing otherwise is dangerous.
> GUAC-1374: socket->__keep_alive_enabled MUST be initialized

- src/guacd/daemon.c
See GUAC-1361.
Tested with two concurrent clients.
> GUAC-1361: listen() need not be present in main loop

- src/protocols/rdp/client.c
- src/protocols/rdp/guac_rdpsnd/rdpsnd_messages.c
- src/protocols/rdp/guac_rdpsnd/rdpsnd_messages.h
- src/protocols/rdp/guac_rdpsnd/rdpsnd_service.c
- src/protocols/rdp/guac_rdpsnd/rdpsnd_service.h
From [GUAC-1196](https://glyptodon.org/jira/browse/GUAC-1196):
> Windows 2012 will silently fail to use RDPDR if RDPSND is not also loaded. Because Guacamole only loads RDPSND if audio support is enabled and present in the browser, explicitly disabling audio or using a browser which lacks full support (IE11) results in RDPDR failing.
> 
> Guacamole's RDP support will already load RDPDR if RDPSND is being loaded, but it should also load RDPSND if RDPDR is being loaded. If audio is explicitly disabled, or the browser lacks full audio support, RDPSND should simply ignore received audio packets.
This change ensures that RDPSND (provided by "guacsnd") is *always* loaded when RDPDR is loaded, even if audio is disabled. When audio is disabled, RDPSND will connect but will ignore the server's …
> GUAC-1196: Always load RDPSND with RDPDR.

- configure.ac
- src/protocols/rdp/client.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
Connecting to the display of a Hyper-V VM requires submitting arbitrary data along RDP's "preconnection PDU" - a means of selecting the so-called "RDP source". This is documented as the "Session Selection Extension" for the RDP protocol: https://msdn.microsoft.com/en-us/library/cc242375.aspx
The "Session Selection Extension" defines two possible fields for selecting the RDP session: a positive integer ID, and an arbitrary string known as the "preconnection BLOB". In practice, the preconnection BLOB is used to select a Hyper-V VM while the ID is left unset.
As far as the RDP protocol is concerned, the true meaning of the ID and BLOB are left opaque. It is up to the server to interpret them.
> GUAC-363: Add support for the RDP preconnection PDU (and thus Hyper-V)

- src/libguac/encode-webp.c
`WEBP_HINT_DEFAULT` is wrong. `WEBP_PRESET_DEFAULT` is correct. Both have the same integer value.
> GUAC-1425: Use proper enum constant for WebPConfigPreset().

- bin/guacctl
- src/terminal/terminal.c
- src/terminal/terminal.h
- src/terminal/terminal_handlers.c
- src/terminal/terminal_handlers.h
This change allows terminal applications to send Guacamole-specific OSC sequences which redirect output to a named pipe stream. Output can be collected within JavaScript by supplying a handler for [the `onpipe` event of `Guacamole.Client`](http://guac-dev.org/doc/guacamole-common-js/Guacamole.Client.html#event:onpipe). If no `onpipe` handler is defined, the pipe stream and its contents will simply be ignored by the client.
Terminal output is redirected to a new named pipe stream by sending:
```
ESC ] 482202 ; NAME ST
```
where:
1. `ESC` is the ANSI "escape" character (0x1B).
2. `]` is the right square bracket character which, following `ESC`, introduces an OSC sequence.
3. `482202` is the number of the Guacamole-specific OSC for redirecting output to a pipe stream.
4. `;` is a semicolon …
> GUAC-1452: Implement OSC sequence for redirecting output to pipe streams

- src/terminal/typescript.c
Bad :-1: 
-----
```c
free(typescript);
close(typescript->data_fd);
```
Good :+1: 
-----
```c
close(typescript->data_fd);
free(typescript);
```
> GUAC-1451: Fix order of resource release in case typescript creation failure.

- src/protocols/rdp/Makefile.am
- src/protocols/rdp/keymaps/ja_jp_qwerty.keymap
Although GUAC-439 claims Guacamole's keyboard input is not dependent on keyboard layout, the half is the case.
On the client side the keycode in the keyboard event propagated from the browser is independent from the keyboard layout, but on the server side it needs to be converted to the appropriate virtual keycode designated by the keyboard layout with which the operating system hosting the desktop is configured.
> GUAC-1410: Add ja-jp keymap

- src/protocols/rdp/Makefile.am
This change simply restores the lexicographical ordering of the keymap files within `Makefile.am`.
> GUAC-1410: Fix keymap ordering in Makefile.am.

- src/guacd/connection.c
We're using `malloc()` / `free()` (from "stdlib.h") and `strerror()` (from "string.h"), and yet those includes are missing.
> GUAC-1389: Add missing includes for guacd's connection.c

- src/common/guac_cursor.c
- src/common/guac_cursor.h
- src/libguac/client.c
- src/libguac/guacamole/client.h
- src/protocols/vnc/user.c
- src/protocols/vnc/user.h
If a user leaves a connection, any existing reference to their `guac_user` structure may suddenly become invalid. While `guac_common_cursor` made an effort to deal with this by updating the user pointer when a user leaves, the race still exists (the window is just smaller).
This change adds a new `guac_client_for_user()` function which allows a callback to be invoked for the given user if and only if the user pointer is actually valid. If they don't exist, `NULL` is passed to the callback instead.
> GUAC-1389: Fix user validity race.

- src/protocols/rdp/client.h
- src/protocols/rdp/rdp.c
- src/protocols/vnc/client.h
- src/protocols/vnc/vnc.c
This change also sets the frame timeouts to zero, relying instead on the automatic duration adjustment.
> GUAC-1389: Stretch RDP and VNC frames until client has caught up.

- src/guacenc/jpeg.c
The `JCS_EXT_BGRX` colorspace is convenient as it's exactly equivalent to Cairo's formats, but it's specific to libjpeg-turbo. Using that colorspace means guacenc fails to build against libjpeg, which is bad.
This change uses libjpeg's standard `JCS_RGB` and translates to Cairo's formats, rather than relying on features specific to libjpeg-turbo.
> GUAC-236: Do not use features specific to libjpeg-turbo. Ensure compatibility with libjpeg.

- configure.ac
- src/common/guac_cursor.c
- src/common/guac_display.c
- src/protocols/rdp/Makefile.am
- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
- src/protocols/rdp/rdp_disp.c
- src/protocols/rdp/rdp_disp.h
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
This change adds a new "reconnect-method" parameter for RDP which accepts two values: "reconnect", which disconnects and reconnects the RDP session when the screen size changes, and "display-update", which uses the "Display Update" channel available with RDP 8.1+. If the parameter is left blank, screen size changes are simply ignored.
> GUAC-1164: Add parameter for automatically reconnecting when display changes

- src/libguac/Makefile.am
- src/protocols/rdp/Makefile.am
Upstream has recently modified the guacamole-server build such that it correctly builds out-of-tree. This is nice, but results in merge conflicts for all backports after that point in history.
For the sake of any future backports, including those slated for 1.6, this change should be backported as well.
> GLEN-115: Backport build changes supporting out-of-tree builds

- src/terminal/display.c
- src/terminal/palette.c
- src/terminal/terminal.c
- src/terminal/terminal/display.h
- src/terminal/terminal/palette.h
- src/terminal/terminal/terminal.h
- src/terminal/terminal_handlers.c
PR #145 added support for console codes that modify the terminal, but was missing backported code from the other half of GUACAMOLE-279 which added core support for terminal mutability. This PR backports those changes, as well.
> GLEN-112: Add support for modification of terminal palette.

- src/protocols/rdp/rdp.c
- src/protocols/vnc/vnc.c
- src/terminal/terminal/terminal_handlers.h
- src/terminal/terminal_handlers.c
These changes, combining upstream [GUACAMOLE-265](https://issues.apache.org/jira/browse/GUACAMOLE-265) and [GUACAMOLE-502](https://issues.apache.org/jira/browse/GUACAMOLE-502), are the server-side changes required by glyptodon/guacamole-client#365.
[GUACAMOLE-265](https://issues.apache.org/jira/browse/GUACAMOLE-265) adds the base support for sending the "name" instruction in response to the terminal code used to change window title, while [GUACAMOLE-502](https://issues.apache.org/jira/browse/GUACAMOLE-502) fixes the behavioral regression in the handling of connection name/title for VNC and RDP which resulted from those changes. Together, these changes add the necessary support in a stable manner.
> GLEN-123: Add support for changing SSH/telnet window title

- src/protocols/ssh/client.c
- src/protocols/ssh/ssh.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
From upstream [GUACAMOLE-384](https://issues.apache.org/jira/browse/GUACAMOLE-384):
> Looks like the terminal is being freed during normal connection cleanup, but prior to the SSH client thread finishing. Depending on timing, attempts to write to the terminal by the SSH client thread segfault since the terminal was already freed.
> 
> This needs to be fixed, but will not affect the stability of connections in practice, as the segfault is occurring during normal disconnect.
> 
> ...
> 
> Yes, that's what I meant by the comment above.
> 
> The thread in this case is the SSH client thread, created to handle the underlying SSH connection after the first user joins:
> 
> https://github.com/apache/incubator-guacamole-server/blob/d35cc7a83e8dfdaa44cbd3b02c70e9407197155a/src/protocols/ssh/user.c#L …
> GLEN-121: Address potential segfault during SSH disconnect.

- src/guacd/move-fd.c
- src/libguac/socket-fd.c
- src/libguac/socket-tee.c
Relevant issues:
* [GUACAMOLE-324](https://issues.apache.org/jira/browse/GUACAMOLE-324) - "Incorrect buffer used in socket write"
* [GUACAMOLE-411](https://issues.apache.org/jira/browse/GUACAMOLE-411) - "guacd_send_fd call's sendmsg with uninitialized buffer"
* [GUACAMOLE-489](https://issues.apache.org/jira/browse/GUACAMOLE-489) - "Secondary socket of "tee" socket is not threadsafe"
> GLEN-122: Backport fixes for buffer handling and threadsafety

- configure.ac
- src/guacd/.gitignore
- src/guacd/Makefile.am
- src/guacd/man/guacd.8.in
- src/guacd/man/guacd.conf.5.in
- src/guacenc/.gitignore
- src/guacenc/Makefile.am
- src/guacenc/man/guacenc.1.in
Note that this change also includes a commit which cherry-picks the following upstream commits:
* 76a6e41 GUACAMOLE-423: Automatically populate package version within manpages.
* 139251e GUACAMOLE-492: Remove guaclog binary erroneously added to source tree.
This has been done so that the version numbers within the documentation (man pages) are also updated.
> GLEN-139: Add Glyptodon Enterprise version number suffix.

- src/protocols/ssh/Makefile.am
- src/protocols/ssh/pipe.c
- src/protocols/ssh/pipe.h
- src/protocols/ssh/user.c
- src/protocols/telnet/Makefile.am
- src/protocols/telnet/pipe.c
- src/protocols/telnet/pipe.h
- src/protocols/telnet/user.c
- src/terminal/Makefile.am
- src/terminal/terminal-stdin-stream.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
These changes depend on #168. The merge base will need to be updated to `glyptodon/1.x` once #168 is merged.
> GLEN-173: Allow terminal input to be read from an inbound pipe stream

- bin/guacctl
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
- src/terminal/terminal/terminal_handlers.h
- src/terminal/terminal_handlers.c
These changes depend on #169. The merge base will need to be updated to `glyptodon/1.x` once #169 is merged.
> GLEN-160: Allow scrollback buffer size to be configured

- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
These changes depend on #171. The merge base will need to be updated to `glyptodon/1.x` once #171 is merged.
> GLEN-161: Allow SSH locale to be explicitly set

- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
These changes depend on #172. The merge base will need to be updated to `glyptodon/1.x` once #172 is merged.
> GLEN-162: Add support for timezone redirection

- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp_cliprdr.c
- src/protocols/rdp/rdp_settings.c
- src/protocols/rdp/rdp_settings.h
- src/protocols/rdp/user.c
- src/protocols/ssh/settings.c
- src/protocols/ssh/settings.h
- src/protocols/ssh/ssh.c
- src/protocols/ssh/user.c
- src/protocols/telnet/settings.c
- src/protocols/telnet/settings.h
- src/protocols/telnet/telnet.c
- src/protocols/telnet/user.c
- src/protocols/vnc/clipboard.c
- src/protocols/vnc/settings.c
- src/protocols/vnc/settings.h
- src/protocols/vnc/user.c
- src/terminal/select.c
- src/terminal/terminal.c
- src/terminal/terminal/terminal.h
These changes depend on #173. The merge base will need to be updated to `glyptodon/1.x` once #173 is merged.
**NOTE:** These changes are also being backported to GLEN 2.x via #167.
> GLEN-158: Allow clipboard access to be disabled within GLEN 1.x

- configure.ac
- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/channels/rail.c
- src/protocols/rdp/gdi.c
- src/protocols/rdp/gdi.h
- src/protocols/rdp/rdp.c
- src/protocols/rdp/settings.c
- src/protocols/rdp/settings.h
This change backports the fixes for all known regressions from the Apache Guacamole 1.1.0 migration to FreeRDP 2.0.0 which have been accepted and merged upstream for the 1.2.0 release.
Except for these specific issues, there have been no other regressions encountered which were not due to FreeRDP 2.0.0-rc0 as packaged by Ubuntu 18.04.
> GLEN-235: Backport fixes for known regressions related to the FreeRDP 2.0.0 migration.

- Dockerfile
- configure.ac
- src/guacd/log.c
- src/libguac/user-handshake.c
As with #206 (from prior to the first RC), this change beings the Glyptodon source tree up-to-date with all changes for the pending upstream 1.3.0 release. Except for version numbers, the code here should be identical to 1.3.0-RC1, and should ultimately be identical to the 1.3.0 release unless there is an RC2.
> GLEN-259: Merge changes from first RC for 1.3.0.

- configure.ac
- src/protocols/vnc/auth.c
- src/protocols/vnc/auth.h
- src/protocols/vnc/vnc.c
The version of libvncclient packaged by CentOS / RHEL 6 lacks the `GetCredential` callback. The guacamole-server source leverages this callback for the VNC support since [GUACAMOLE-514](https://issues.apache.org/jira/browse/GUACAMOLE-514) (part of Apache Guacamole 1.2.0), resulting in a build failure. With the upcoming GLEN 2.2 release intended to be based off upcoming Apache Guacamole 1.3.0, our builds for the EL6 platform are also currently failing.
This change backports the build fix introduced by [GUACAMOLE-1227](https://issues.apache.org/jira/browse/GUACAMOLE-1227), making the relevant code conditional and correcting the build.
> GLEN-259: Backport fix for VNC build on EL6.

- configure.ac
- src/libguac/id.c
- src/libguac/tests/Makefile.am
- src/libguac/tests/id/generate.c
RHEL 6 does not include a uuid-devel package (the OSSP UUID library). It _does_ provide a libuuid-devel package (the library from util-linux). For our builds to leverage RHEL rather than CentOS (see [comment on GLEN-261](https://jira.glyptodon.com/browse/GLEN-261?focusedCommentId=32453&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-32453)), the recent upstream support for libuuid needs to be backported.
> GLEN-261: Backport support for libuuid to GLEN 1.x.

- configure.ac
- src/libguac/id.c
- src/libguac/tests/Makefile.am
- src/libguac/tests/id/generate.c
RHEL 6 does not include a uuid-devel package (the OSSP UUID library). It _does_ provide a libuuid-devel package (the library from util-linux). For our builds to leverage RHEL rather than CentOS (see [comment on GLEN-261](https://jira.glyptodon.com/browse/GLEN-261?focusedCommentId=32453&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-32453)), the recent upstream support for libuuid needs to be backported.
> GLEN-261: Backport support for libuuid to GLEN 2.x.

- configure.ac
- src/common-ssh/Makefile.am
- src/common-ssh/buffer.c
- src/common-ssh/common-ssh/buffer.h
- src/common-ssh/common-ssh/dsa-compat.h
- src/common-ssh/common-ssh/rsa-compat.h
- src/common-ssh/dsa-compat.c
- src/common-ssh/key.c
- src/common-ssh/rsa-compat.c
- src/common-ssh/ssh.c
- src/guacd/daemon.c
While the Glyptodon Enterprise 2.x build works fine against RHEL 8, the Glyptodon Enterprise 1.x build fails due to the use of the older OpenSSL API.
> GLEN-182: Backport support for OpenSSL 1.1.

- src/terminal/typescript.c
A warning regarding `sprintf()` specific to GCC 7 was corrected upstream via [GUACAMOLE-500](https://issues.apache.org/jira/browse/GUACAMOLE-500) for 1.0.0 and later. As the base version of Guacamole packaged by Glyptodon Enterprise 1.x is earlier than this (0.9.12-incubating), the build fails with a warning on RHEL 8.
> GLEN-182: Correct GCC 7 sprintf() warning resulting in GLEN 1.x build failure on RHEL 8.

- src/protocols/rdp/channels/audio-input/audio-buffer.c
- src/protocols/rdp/channels/audio-input/audio-buffer.h
- src/protocols/rdp/channels/cliprdr.c
- src/protocols/rdp/channels/common-svc.c
- src/protocols/rdp/channels/disp.c
- src/protocols/rdp/channels/disp.h
- src/protocols/rdp/channels/rail.c
- src/protocols/rdp/channels/rdpei.c
- src/protocols/rdp/channels/rdpei.h
- src/protocols/rdp/client.c
- src/protocols/rdp/input.c
- src/protocols/rdp/keyboard.c
- src/protocols/rdp/plugins/guacai/guacai-messages.c
- src/protocols/rdp/rdp.c
- src/protocols/rdp/rdp.h
The RDP specification for the AUDIO_INPUT channel requires that all audio be sent in packets of a specific size. Guacamole does correctly limit itself to sending packets of this size to the RDP server, but will send quite a few of these packets all at once if it has received more audio data than the RDP packet size. This is OK in principle (the Guacamole client should be able to send audio in packets of whatever size it chooses), but may overwhelm the software running within the RDP server if the amount of data received exceeds the available buffer space, resulting in dropped samples.
As there is no way to know the size of the remote audio buffer, we need to instead ensure that audio is streamed as close to real time as possible, with each audio packet of N bytes not being sent until …
> GLEN-242: Automatically throttle RDP audio input transmission rate.
